In [2]:
import pandas as pd

In [17]:
df = pd.read_csv("videos.csv")
df.head()

,title,topic,url,publish_date,likes,comments,shares,collections,views,subscribers
0,This powder changes color like magic,science,https://vt.tiktok.com/ZSxExR68v/,2022/4/19,4547000,27000,192000,196000,29177000,10546000
1,What if Time isn't real?,science,https://vt.tiktok.com/ZSxExMr85/,2026/5/2,580000,2738,59000,74000,2669000,11000
2,Part 1: Earth Has Been Falling for 4.6 Billion...,science,https://vt.tiktok.com/ZSxExFVd4/,2026/2/28,472000,5395,24000,53000,4565000,546000
3,Today we look at some sound wave physics!,science,https://vt.tiktok.com/ZSxExj6M5/,2023/5/16,1086000,5562,44000,81000,12900000,385000
4,Scientists discovery breaks a fundamental rule...,science,https://vt.tiktok.com/ZSxExFNAr/,2026/4/21,164000,939,24000,24000,1444000,40000

In [18]:
df['engagement_rate'] = (df['likes']+df['comments']+df['shares']+df['collections'])/df['views']
df.head()

,title,topic,url,publish_date,likes,comments,shares,collections,views,subscribers,engagement_rate
0,This powder changes color like magic,science,https://vt.tiktok.com/ZSxExR68v/,2022/4/19,4547000,27000,192000,196000,29177000,10546000,0.170065
1,What if Time isn't real?,science,https://vt.tiktok.com/ZSxExMr85/,2026/5/2,580000,2738,59000,74000,2669000,11000,0.268167
2,Part 1: Earth Has Been Falling for 4.6 Billion...,science,https://vt.tiktok.com/ZSxExFVd4/,2026/2/28,472000,5395,24000,53000,4565000,546000,0.121445
3,Today we look at some sound wave physics!,science,https://vt.tiktok.com/ZSxExj6M5/,2023/5/16,1086000,5562,44000,81000,12900000,385000,0.094307
4,Scientists discovery breaks a fundamental rule...,science,https://vt.tiktok.com/ZSxExFNAr/,2026/4/21,164000,939,24000,24000,1444000,40000,0.147465

In [19]:
df['ap_rank'] = df['views'].rank(ascending = False)
df['er_rank'] = df['engagement_rate'].rank(ascending = False)
df['avg_rank_score'] = (df['ap_rank']+df['er_rank'])/2 
df['avg_rank'] = df['avg_rank_score'].rank()

df.head()

,title,topic,url,publish_date,likes,comments,shares,collections,views,subscribers,engagement_rate,ap_rank,er_rank,avg_rank_score,avg_rank
0,This powder changes color like magic,science,https://vt.tiktok.com/ZSxExR68v/,2022/4/19,4547000,27000,192000,196000,29177000,10546000,0.170065,2.0,4.0,3.0,1.0
1,What if Time isn't real?,science,https://vt.tiktok.com/ZSxExMr85/,2026/5/2,580000,2738,59000,74000,2669000,11000,0.268167,19.0,1.0,10.0,3.0
2,Part 1: Earth Has Been Falling for 4.6 Billion...,science,https://vt.tiktok.com/ZSxExFVd4/,2026/2/28,472000,5395,24000,53000,4565000,546000,0.121445,16.0,18.0,17.0,12.5
3,Today we look at some sound wave physics!,science,https://vt.tiktok.com/ZSxExj6M5/,2023/5/16,1086000,5562,44000,81000,12900000,385000,0.094307,7.0,29.0,18.0,14.0
4,Scientists discovery breaks a fundamental rule...,science,https://vt.tiktok.com/ZSxExFNAr/,2026/4/21,164000,939,24000,24000,1444000,40000,0.147465,25.0,9.0,17.0,12.5