In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("videos.csv")
df.head()

,title,topic,url,publish_date,likes,comments,shares,collections,views,subscribers,group,id
0,This powder changes color like magic,science,https://vt.tiktok.com/ZSxExR68v/,2022/4/19,4547000,27000,192000,196000,29177000,10546000,NaN,NaN
1,What if Time isn't real?,science,https://vt.tiktok.com/ZSxExMr85/,2026/5/2,580000,2738,59000,74000,2669000,11000,b,S01
2,Part 1: Earth Has Been Falling for 4.6 Billion...,science,https://vt.tiktok.com/ZSxExFVd4/,2026/2/28,472000,5395,24000,53000,4565000,546000,NaN,NaN
3,Today we look at some sound wave physics!,science,https://vt.tiktok.com/ZSxExj6M5/,2023/5/16,1086000,5562,44000,81000,12900000,385000,a,S02
4,Scientists discovery breaks a fundamental rule...,science,https://vt.tiktok.com/ZSxExFNAr/,2026/4/21,164000,939,24000,24000,1444000,40000,b,S02

In [3]:
df['engagement_rate'] = (df['likes']+df['comments']+df['shares']+df['collections'])/df['views']
df.head()

,title,topic,url,publish_date,likes,comments,shares,collections,views,subscribers,group,id,engagement_rate
0,This powder changes color like magic,science,https://vt.tiktok.com/ZSxExR68v/,2022/4/19,4547000,27000,192000,196000,29177000,10546000,NaN,NaN,0.170065
1,What if Time isn't real?,science,https://vt.tiktok.com/ZSxExMr85/,2026/5/2,580000,2738,59000,74000,2669000,11000,b,S01,0.268167
2,Part 1: Earth Has Been Falling for 4.6 Billion...,science,https://vt.tiktok.com/ZSxExFVd4/,2026/2/28,472000,5395,24000,53000,4565000,546000,NaN,NaN,0.121445
3,Today we look at some sound wave physics!,science,https://vt.tiktok.com/ZSxExj6M5/,2023/5/16,1086000,5562,44000,81000,12900000,385000,a,S02,0.094307
4,Scientists discovery breaks a fundamental rule...,science,https://vt.tiktok.com/ZSxExFNAr/,2026/4/21,164000,939,24000,24000,1444000,40000,b,S02,0.147465

In [4]:
df["publish_date"] = pd.to_datetime(df["publish_date"])

In [5]:
collection_date = pd.to_datetime("2026-06-03")

df["age"] = (
    collection_date - df["publish_date"]
).dt.days

df["tp"] = df["views"] / np.log1p(df["age"]+1)

df.head()

,title,topic,url,publish_date,likes,comments,shares,collections,views,subscribers,group,id,engagement_rate,age,tp
0,This powder changes color like magic,science,https://vt.tiktok.com/ZSxExR68v/,2022-04-19,4547000,27000,192000,196000,29177000,10546000,NaN,NaN,0.170065,1506,3.986724e+06
1,What if Time isn't real?,science,https://vt.tiktok.com/ZSxExMr85/,2026-05-02,580000,2738,59000,74000,2669000,11000,b,S01,0.268167,32,7.568710e+05
2,Part 1: Earth Has Been Falling for 4.6 Billion...,science,https://vt.tiktok.com/ZSxExFVd4/,2026-02-28,472000,5395,24000,53000,4565000,546000,NaN,NaN,0.121445,95,9.978772e+05
3,Today we look at some sound wave physics!,science,https://vt.tiktok.com/ZSxExj6M5/,2023-05-16,1086000,5562,44000,81000,12900000,385000,a,S02,0.094307,1114,1.838260e+06
4,Scientists discovery breaks a fundamental rule...,science,https://vt.tiktok.com/ZSxExFNAr/,2026-04-21,164000,939,24000,24000,1444000,40000,b,S02,0.147465,43,3.793349e+05

In [6]:
df['tp_rank'] = df['tp'].rank(ascending = False)
df['er_rank'] = df['engagement_rate'].rank(ascending = False)
df['avg_rank_score'] = (df['tp_rank']+df['er_rank'])/2 
df['avg_rank'] = df['avg_rank_score'].rank()

df.head()

,title,topic,url,publish_date,likes,comments,shares,collections,views,subscribers,group,id,engagement_rate,age,tp,tp_rank,er_rank,avg_rank_score,avg_rank
0,This powder changes color like magic,science,https://vt.tiktok.com/ZSxExR68v/,2022-04-19,4547000,27000,192000,196000,29177000,10546000,NaN,NaN,0.170065,1506,3.986724e+06,3.0,4.0,3.5,1.0
1,What if Time isn't real?,science,https://vt.tiktok.com/ZSxExMr85/,2026-05-02,580000,2738,59000,74000,2669000,11000,b,S01,0.268167,32,7.568710e+05,17.0,1.0,9.0,2.0
2,Part 1: Earth Has Been Falling for 4.6 Billion...,science,https://vt.tiktok.com/ZSxExFVd4/,2026-02-28,472000,5395,24000,53000,4565000,546000,NaN,NaN,0.121445,95,9.978772e+05,14.0,18.0,16.0,10.0
3,Today we look at some sound wave physics!,science,https://vt.tiktok.com/ZSxExj6M5/,2023-05-16,1086000,5562,44000,81000,12900000,385000,a,S02,0.094307,1114,1.838260e+06,10.0,29.0,19.5,15.5
4,Scientists discovery breaks a fundamental rule...,science,https://vt.tiktok.com/ZSxExFNAr/,2026-04-21,164000,939,24000,24000,1444000,40000,b,S02,0.147465,43,3.793349e+05,23.0,9.0,16.0,10.0